# Generated by Django 3.1.3 on 2020-11-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(blank=True, default=None, null=True, path='/img'),
        ),
    ]
