# Generated by Django 3.1.3 on 2020-11-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201129_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
